trigger:
  branches:
    include:
      - main

pool:
  name: OCI_VMS

jobs:

- job: Deploy_VM01
  displayName: "Deploy na VM-01"
  pool:
    name: OCI_VMS
    demands:
      - agent.name -equals vm-01
  steps:
    - checkout: self
    - script: |
        cd /opt/n8n-deploy
        git fetch --all
        git reset --hard origin/main
        docker compose pull
        docker compose up -d
        docker image prune -f
      displayName: Deploy VM-01

- job: Deploy_VM02
  displayName: "Deploy na VM-02"
  pool:
    name: OCI_VMS
    demands:
      - agent.name -equals vm-02
  steps:
    - checkout: self
    - script: |
        cd /opt/n8n-deploy
        git fetch --all
        git reset --hard origin/main
        docker compose pull n8n
        docker compose up -d n8n
        docker image prune -f
      displayName: Deploy VM-02
