trigger:
  branches:
    include:
      - main

pool:
  name: OCI_VMS
  demands:
    - Agent.Name -equals vm-01

steps:

  - script: |
      echo ">> Atualizando repositório local..."
      cd /home/ubuntu/n8n-deploy
      git fetch --all
      git reset --hard origin/main

      echo ">> Atualizando imagens Docker..."
      docker compose pull

      echo ">> Subindo containers..."
      docker compose up -d

      echo ">> Limpando imagens antigas..."
      docker image prune -f
    displayName: "Deploy automático n8n"
